=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Leistungskurvendefinition.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Leistungskurvendefinition.schema.json",
  "title": "Leistungskurvendefinition",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "LEISTUNGSKURVENDEFINITION"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "beginndatum": {
      "type": "string",
      "format": "date-time",
      "description": "beginndatum"
    },
    "endedatum": {
      "type": "string",
      "format": "date-time",
      "description": "endedatum"
    },
    "version": {
      "type": "string",
      "format": "date-time",
      "description": "version"
    },
    "code": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "CODE_",
          "length": 4
        }
      },
      "description": "code"
    },
    "notwendigkeit": {
      "$ref": "../enum/DefinitionenNotwendigkeit.schema.json"
    },
    "leistungskurven": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../com/Leistungskurve.schema.json"
      },
      "description": "leistungskurven"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Leistungskurvendefinition.json
{
  "boTyp": "LEISTUNGSKURVENDEFINITION",
  "versionStruktur": "1",
  "beginndatum": "1922-01-12T02:27:31.0Z",
  "endedatum": "1891-05-29T19:58:18.0Z",
  "version": "1938-07-07T21:51:05.0Z",
  "code": "CODE_0010",
  "notwendigkeit": "DEFINITIONEN_WERDEN_VERWENDET",
  "leistungskurven": [
    {
      "code": "CODE_0111",
      "aenderungszeitpunkt": "1920-11-12T07:51:42.0Z",
      "haeufigkeit": "JAEHRLICH",
      "uebermittelbarkeit": "ELEKTRONISCH",
      "schwellwert": {
        "obererSchwellwert": 15.5,
        "untererSchwellwert": 6.5,
        "konfigurationsprodukt": "KONF_1100"
      },
      "konfigurationsprodukt": "KONF_0001"
    }
  ]
}
