=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Lokationsbuendel.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Lokationsbuendel.schema.json",
  "title": "Lokationsbuendel",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "LOKATIONSBUENDEL"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1"
    },
    "lokationsbuendelstrukturId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      }
    },
    "lokationsbuendelNummer": {
      "type": "integer"
    },
    "standardisierteLokationsbuendelstruktur": {
      "type": "boolean"
    },
    "datenqualitaet": {
      "$ref": "../enum/Datenqualitaet.schema.json"
    },
    "gueltigkeitszeitraum": {
      "$ref": "../com/Zeitraum.schema.json"
    },
    "zuordnungObjectcode": {
      "type": "array",
      "items": {
        "$ref": "../com/ZuordnungObjectcode.schema.json"
      }
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Lokationsbuendel.json
{
  "boTyp": "LOKATIONSBUENDEL",
  "versionStruktur": "1",
  "lokationsbuendelstrukturId": "03606523785",
  "lokationsbuendelNummer": 80912307,
  "standardisierteLokationsbuendelstruktur": false,
  "datenqualitaet": "KEINE_DATEN_ERWARTET",
  "gueltigkeitszeitraum": {
    "zeiteinheit": "VIERTEL_STUNDE",
    "dauer": 0,
    "startdatum": "1895-09-01T16:37:08.0Z",
    "enddatum": "1903-12-14T22:54:38.0Z",
    "einheit": "STUNDE",
    "ableseZeitraum": "972638",
    "abrechnungsZeitraum": "174399",
    "zeitraumText": "ullamco",
    "zeitraumId": 9
  },
  "zuordnungObjectcode": [
    {
      "referenzLokationsTyp": "MALO",
      "referenzLokationsId": "38328496354",
      "vorgelagerteLokationTyp": "MALO",
      "vorgelagerteLokationId": "60214676319",
      "objectcode": [
        {
          "objectcode": "CODE_101011",
          "lokationsbuendelNummer": 10
        }
      ],
      "referenzMarktlokationTechnischeRessource": [
        "82683650808"
      ]
    }
  ]
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Lokationsbuendel.json
{
  "boTyp": "LOKATIONSBUENDEL",
  "versionStruktur": "1",
  "lokationsbuendelstrukturId": "93715456522",
  "lokationsbuendelNummer": 20248209,
  "standardisierteLokationsbuendelstruktur": false,
  "datenqualitaet": "GUELTIGE_DATEN",
  "gueltigkeitszeitraum": {
    "zeiteinheit": "SEKUNDE",
    "dauer": 2,
    "startdatum": "1954-07-10T14:16:49.0Z",
    "enddatum": "1946-08-29T16:11:04.0Z",
    "einheit": "JAHR",
    "ableseZeitraum": "637015",
    "abrechnungsZeitraum": "935333",
    "zeitraumText": "velit",
    "zeitraumId": 9
  },
  "zuordnungObjectcode": [
    {
      "referenzLokationsTyp": "NELO",
      "referenzLokationsId": "33473227261",
      "vorgelagerteLokationTyp": "NELO",
      "vorgelagerteLokationId": "43215940245",
      "objectcode": [
        {
          "objectcode": "CODE_001100",
          "lokationsbuendelNummer": 1
        }
      ],
      "referenzMarktlokationTechnischeRessource": [
        "08531982527"
      ]
    }
  ]
}
