=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Marktteilnehmer.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Marktteilnehmer.schema.json",
  "title": "Marktteilnehmer",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "MARKTTEILNEHMER"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "geschaeftspartnerrolle": {
      "$ref": "../enum/Geschaeftspartnerrolle.schema.json",
      "description": "Rolle, die der Geschäftspartner hat (z.B. Interessent, Kunde)."
    },
    "anrede": {
      "type": "string",
      "faker": "person.prefix",
      "description": "Die Anrede für den GePa, Z.B. Herr."
    },
    "name1": {
      "type": "string",
      "faker": "person.lastName",
      "description": "Erster Teil des Namens. Hier kann der Firmenname oder bei Privatpersonen\nbeispielsweise der Nachname dargestellt werden. Beispiele: Yellow Strom GmbH\noder Hagen"
    },
    "name2": {
      "type": "string",
      "faker": "person.firstName",
      "description": "Zweiter Teil des Namens. Hier kann der eine Erweiterung zum Firmennamen oder\nbei Privatpersonen beispielsweise der Vorname dargestellt werden. Beispiele:\nBereich Süd oder Nina"
    },
    "name3": {
      "type": "string",
      "description": "Dritter Teil des Namens. Hier können weitere Ergänzungen zum Firmennamen oder\nbei Privatpersonen Zusätze zum Namen dargestellt werden. Beispiele: und Afrika\noder Sängerin"
    },
    "name4": {
      "type": "string",
      "description": "name4"
    },
    "partneradresse": {
      "$ref": "../com/Adresse.schema.json",
      "description": "Adresse des Geschäftspartners, an der sich der Hauptsitz befindet. Details"
    },
    "gewerbekennzeichnung": {
      "type": "boolean",
      "description": "Kennzeichnung ob es sich um einen Gewerbe/Unternehmen (gewerbeKennzeichnung = true)\noder eine Privatperson handelt. (gewerbeKennzeichnung = false)"
    },
    "externeKundenummerLieferant": {
      "type": "string",
      "description": "externeKundenummerLieferant"
    },
    "marktrolle": {
      "$ref": "../enum/Marktrolle.schema.json",
      "description": "Gibt im Klartext die Bezeichnung der Marktrolle an."
    },
    "rollencodenummer": {
      "type": "string",
      "faker": {
        "string.numeric": 9
      },
      "description": "Gibt die Codenummer der Marktrolle an."
    },
    "rollencodetyp": {
      "$ref": "../enum/Rollencodetyp.schema.json",
      "description": "Gibt den Typ des Codes an."
    },
    "umsatzsteuerId": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "DE",
          "length": 9
        }
      },
      "description": "Die Umsatzsteuer-ID des Geschäftspartners. Beispiel: DE 813281825"
    },
    "steuernummer": {
      "type": "string",
      "faker": {
        "string.numeric": 9
      },
      "description": "Die Steuernummer-ID des Geschäftspartners. Beispiel: 30120345678"
    },
    "ansprechpartner": {
      "$ref": "../bo/Ansprechpartner.schema.json",
      "description": "Ansprechpartner as in EDIFACT NAD+MS, that includes e.g. the email address of a natural person."
    },
    "makoadresse": {
      "type": "string",
      "description": "Die 1:1-Kommunikationsadresse des Marktteilnehmers. Diese wird in der\nMarktkommunikation verwendet."
    },
    "downloadlinkZertifikat": {
      "type": "string",
      "faker": "internet.url",
      "description": "downloadlinkZertifikat"
    },
    "amtsgericht": {
      "type": "string",
      "faker": "location.city",
      "description": "Amtsgericht bzw Handelsregistergericht, das die Handelsregisternummer herausgegeben hat"
    },
    "hrnummer": {
      "type": "string",
      "faker": {
        "string.numeric": 6
      },
      "description": "Handelsregisternummer des Geschäftspartners"
    },
    "website": {
      "type": "string",
      "faker": "internet.url",
      "description": "Internetseite des Marktpartners. Beispiel: www.mp-energie.de"
    },
    "faxnummer": {
      "type": "string",
      "faker": "phone.number",
      "description": "faxnummer"
    },
    "kommunikationsrolle": {
      "$ref": "../enum/Kommunikationsrolle.schema.json"
    },
    "weiterverpflichtet": {
      "type": "boolean",
      "description": "weiterverpflichtet"
    },
    "kommunikationsparameter": {
      "$ref": "../com/Kommunikationsparameter.schema.json"
    },
    "messstellenbetreiberEigenschaft": {
      "$ref": "../enum/MSBEigenschaft.schema.json"
    },
    "bankverbindung": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../com/Bankverbindung.schema.json"
      },
      "description": "Bankverbindung"
    },
    "erreichbarkeit": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../com/Erreichbarkeit.schema.json"
      },
      "description": "Die Erreichbarkeit eines Unternehmens an Werktagen."
    },
    "ipAdresse": {
      "type": "string",
      "faker": "internet.ip",
      "description": "ipAdresse"
    },
    "ipRange": {
      "$ref": "../com/IpRange.schema.json"
    },
    "zuordnungVon": {
      "type": "string",
      "format": "date-time",
      "description": "Startdatum der Zuordnung des Marktteilnehmers"
    },
    "zuordnungBis": {
      "type": "string",
      "format": "date-time",
      "description": "Enddatum der Zuordnung des Marktteilnehmers"
    },
    "bilanzkreis": {
      "type": "string",
      "description": "Bilanzkreis"
    },
    "verwendungszweckBilanzkreis": {
      "$ref": "../enum/VerwendungszweckBilanzkreis.schema.json",
      "description": "Verwendungszweck des Bilanzkreises"
    },
    "bilanzkreise": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../bo/Bilanzkreis.schema.json"
      },
      "description": "Bilanzkreise"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Marktteilnehmer.json
{
  "boTyp": "MARKTTEILNEHMER",
  "versionStruktur": "1",
  "geschaeftspartnerrolle": "EIGENTUEMER",
  "anrede": "Prof. Dr.",
  "name1": "Niedermeier",
  "name2": "Joseph",
  "name3": "commodo dolor est sed",
  "name4": "non",
  "partneradresse": {
    "postleitzahl": "63782",
    "ort": "Neumünster",
    "strasse": "Kämper Weg",
    "hausnummer": "76b",
    "postfach": "mollit eu cillum deserunt laboris",
    "adresszusatz": "esse laboris proident amet",
    "coErgaenzung": "irure reprehenderit qui nostrud",
    "landescode": "LC",
    "ortsteil": "Alt Fine",
    "zusatzInformation": {
      "zusatz1": "amet in veniam",
      "zusatz2": "dolor id eiusmod qui",
      "zusatz3": "velit exercitation tempor",
      "zusatz4": "in eiusmod enim",
      "zusatz5": "nostrud veniam ullamco exercitation"
    }
  },
  "gewerbekennzeichnung": true,
  "externeKundenummerLieferant": "nostrud est esse",
  "marktrolle": "NB",
  "rollencodenummer": "120915261",
  "rollencodetyp": "GS1",
  "umsatzsteuerId": "DE110001011",
  "steuernummer": "314310327",
  "ansprechpartner": {
    "boTyp": "ANSPRECHPARTNER",
    "versionStruktur": "1",
    "nachname": "Illing",
    "eMailAdresse": "Mads.Helpling41@hotmail.com",
    "rufnummern": [
      {
        "nummerntyp": "FAX_ZENTRALE",
        "rufnummer": "(0240) 907673487"
      }
    ]
  },
  "makoadresse": "id commodo",
  "downloadlinkZertifikat": "https://wunderhubsch-virus.org/",
  "amtsgericht": "Süd Iven",
  "hrnummer": "772273",
  "website": "https://spritzig-elefant.name/",
  "faxnummer": "+49-5273-73095345",
  "kommunikationsrolle": "ABRECHNUNGSPROZESSE",
  "weiterverpflichtet": false,
  "kommunikationsparameter": {
    "zieladresse": {
      "zieladresse1": "occaecat ullamco cupidatat exercitation Ut",
      "zieladresse2": "voluptate ex",
      "zieladresse3": "Lorem dolor enim",
      "zieladresse4": "nisi officia",
      "zieladresse5": "in aliqua irure"
    },
    "zertifikatsAussteller": {
      "zertifikatsAussteller1": "proident Ut veniam",
      "zertifikatsAussteller2": "minim ut",
      "zertifikatsAussteller3": "sit est",
      "zertifikatsAussteller4": "ea in enim voluptate",
      "zertifikatsAussteller5": "esse eu et cillum"
    },
    "zertifikatsNutzer": {
      "zertifikatsNutzer1": "irure tempor",
      "zertifikatsNutzer2": "nisi ullamco consectetur Duis in",
      "zertifikatsNutzer3": "Ut magna elit dolore",
      "zertifikatsNutzer4": "velit sint",
      "zertifikatsNutzer5": "est dolor aliqua cillum"
    }
  },
  "messstellenbetreiberEigenschaft": "GRUNDZUSTAENDIGER_MESSSTELLENBETREIBER",
  "bankverbindung": [
    {
      "verwendungszweck": "BV_ZAHLUNG_MMMA",
      "iban": "GT219296845A4122535042A1087R",
      "kontoinhaber": "Frau Janne Frey",
      "bic": "EYAVPFJMXXX",
      "kreditinstitut": "Kampf Gruppe"
    }
  ],
  "erreichbarkeit": [
    {
      "verfuegbarkeit": "DONNERSTAG",
      "zeit": "et adipisicing"
    }
  ],
  "ipAdresse": "38.253.21.31",
  "ipRange": {
    "untereGrenze": "edaa:ba87:bf4d:b5ea:fda7:ee3e:4c6c:8736",
    "obereGrenze": "da42:6665:2d2e:20be:f4b0:cddc:1e36:b7b8"
  },
  "zuordnungVon": "1894-04-15T10:42:51.0Z",
  "zuordnungBis": "1915-10-04T21:18:17.0Z",
  "bilanzkreis": "do fugiat",
  "verwendungszweckBilanzkreis": "ERZEUGENDE_MARKTLOKATION_KWKG",
  "bilanzkreise": [
    {
      "boTyp": "BILANZKREIS",
      "versionStruktur": "1",
      "bezeichnung": "magna fugiat aliquip eu",
      "prioritaet": 4,
      "verwendungszweckBilanzkreis": "VERBRAUCHENDE_MARKTLOKATION"
    }
  ]
}
