=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Sperrauftrag.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Sperraufrag.schema.json",
  "title": "Sperrauftrag",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "SPERRAUFTRAG"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1"
    },
    "treffpunkt": {
      "$ref": "../com/Adresse.schema.json"
    },
    "sperrauftragsart": {
      "$ref": "../enum/Sperrauftragsart.schema.json"
    },
    "sperrauftragsstatus": {
      "$ref": "../enum/Auftragsstatus.schema.json"
    },
    "sperrauftragsablehngrund": {
      "$ref": "../enum/Sperrauftragsablehngrund.schema.json"
    },
    "sperrauftragsverhinderungsgrund": {
      "$ref": "../enum/Sperrauftragsverhinderungsgrund.schema.json"
    },
    "zaehlernummer": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "ZAEHLER_",
          "length": 6
        }
      }
    },
    "istVomGerichtsvollzieherAngeordnet": {
      "type": "boolean"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Sperrauftrag.json
{
  "boTyp": "SPERRAUFTRAG",
  "versionStruktur": "1",
  "treffpunkt": {
    "postleitzahl": "64677",
    "ort": "Neu Kira",
    "strasse": "Regensburger Str.",
    "hausnummer": "3",
    "postfach": "qui exercitation laboris",
    "adresszusatz": "sunt ex",
    "coErgaenzung": "ipsum cillum sed",
    "landescode": "VU",
    "ortsteil": "Wilhelmshaven",
    "zusatzInformation": {
      "zusatz1": "voluptate incididunt pariatur non do",
      "zusatz2": "sunt dolore",
      "zusatz3": "deserunt sed",
      "zusatz4": "sed nisi",
      "zusatz5": "ut nulla veniam"
    }
  },
  "sperrauftragsart": "ENTSPERREN",
  "sperrauftragsstatus": "ZUGESTIMMT",
  "sperrauftragsablehngrund": "ANDERER_FEHLER",
  "sperrauftragsverhinderungsgrund": "TECHNISCHER_VERHINDERUNGSGRUND",
  "zaehlernummer": "ZAEHLER_111011",
  "istVomGerichtsvollzieherAngeordnet": false
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Sperrauftrag.json
{
  "boTyp": "SPERRAUFTRAG",
  "versionStruktur": "1",
  "treffpunkt": {
    "postleitzahl": "76019",
    "ort": "Jenniferland",
    "strasse": "Burgweg",
    "hausnummer": "67",
    "postfach": "cillum reprehenderit esse ut ipsum",
    "adresszusatz": "mollit laborum",
    "coErgaenzung": "reprehenderit sit ut quis nisi",
    "landescode": "PL",
    "ortsteil": "Hattingen",
    "zusatzInformation": {
      "zusatz1": "occaecat ut",
      "zusatz2": "velit irure sit sunt",
      "zusatz3": "nulla",
      "zusatz4": "laborum ea velit officia amet",
      "zusatz5": "fugiat et in sed"
    }
  },
  "sperrauftragsart": "SPERREN",
  "sperrauftragsstatus": "UMGESETZT",
  "sperrauftragsablehngrund": "FALSCHE_SPANNUNGSEBENE",
  "sperrauftragsverhinderungsgrund": "TECHNISCHER_VERHINDERUNGSGRUND",
  "zaehlernummer": "ZAEHLER_000100",
  "istVomGerichtsvollzieherAngeordnet": true
}
