=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Summenzeitreihe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Summenzeitreihe.schema.json",
  "title": "Summenzeitreihe",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "SUMMENZEITREIHE"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "zaehlpunktId": {
      "type": "string",
      "description": "ID des Zaehlpunkts"
    },
    "versionZeitreihe": {
      "type": "string",
      "description": "Version der Zeitreihe"
    },
    "bilanzkreis": {
      "type": "string",
      "description": "Bilanzkreis"
    },
    "bilanzkreisAn": {
      "type": "string",
      "description": "BilanzkreisAn"
    },
    "bilanzkreisVon": {
      "type": "string",
      "description": "BilanzkreisVon"
    },
    "bilanzierteEnergiemenge": {
      "$ref": "../com/Menge.schema.json",
      "description": "Bilanzierte Energiemenge"
    },
    "bilanzierteAusfallmenge": {
      "$ref": "../com/Menge.schema.json",
      "description": "Bilanzierte Ausfallmenge"
    },
    "bilanzierungsbeginn": {
      "type": "string",
      "format": "date-time",
      "description": "bilanzierungsbeginn"
    },
    "bilanzierungsgebiet": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      },
      "description": "Bilanzierungsgebiet(e)"
    },
    "bezeichnung": {
      "$ref": "../enum/Bezeichnung.schema.json",
      "description": "Bezeichnung"
    },
    "verantwortlicheMarktrolle": {
      "$ref": "../enum/Marktrolle.schema.json",
      "description": "Verantwortliche Marktrolle"
    },
    "regelzone": {
      "type": "string",
      "description": "Regelzone"
    },
    "zeitreihenart": {
      "$ref": "../enum/Zeitreihenart.schema.json",
      "description": "Art der Zeitreihe (Summen- oder Ueberfuehrungszeitreihe)"
    },
    "zeitreihentyp": {
      "$ref": "../enum/Zeitreihentyp.schema.json",
      "description": "Zeitreihentyp"
    },
    "bezugszeitraum": {
      "$ref": "../enum/Bezugszeitraum.schema.json",
      "description": "Bezugszeitraum der Zeitreihe"
    },
    "netzebene": {
      "$ref": "../enum/Netzebene.schema.json",
      "description": "Netzebene"
    },
    "umspannung": {
      "$ref": "../enum/Netzebene.schema.json",
      "description": "Umspannung"
    },
    "datenstatusZeitreihe": {
      "$ref": "../enum/DatenstatusZeitreihe.schema.json",
      "description": "Datenstatus der Zeitreihe"
    },
    "zuordnungsregel": {
      "$ref": "../enum/Zuordnungsregel.schema.json",
      "description": "Zuordnungsregel der Summenzeitreihe"
    },
    "zeitreihenprodukt": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../com/Zeitreihenprodukt.schema.json"
      },
      "description": "Liste der Zeitreihenprodukte"
    }

  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Summenzeitreihe.json
{
  "boTyp": "SUMMENZEITREIHE",
  "versionStruktur": "1",
  "zaehlpunktId": "reprehenderit",
  "versionZeitreihe": "in enim",
  "bilanzkreis": "quis",
  "bilanzkreisAn": "consequat non enim eiusmod",
  "bilanzkreisVon": "ut pariatur sed amet",
  "bilanzierteEnergiemenge": {
    "wert": 4.25,
    "einheit": "WH",
    "startdatum": "1964-11-11T22:21:41.0Z",
    "enddatum": "1891-09-18T08:16:43.0Z"
  },
  "bilanzierteAusfallmenge": {
    "wert": 4.25,
    "einheit": "ANZAHL",
    "startdatum": "1951-09-24T23:25:29.0Z",
    "enddatum": "1944-08-04T03:24:04.0Z"
  },
  "bilanzierungsbeginn": "1934-07-13T23:01:22.0Z",
  "bilanzierungsgebiet": [
    "ex dolor"
  ],
  "bezeichnung": "ASZR",
  "verantwortlicheMarktrolle": "MSBA",
  "regelzone": "sint Excepteur culpa in",
  "zeitreihenart": "SUMMENZEITREIHE",
  "zeitreihentyp": "TES",
  "bezugszeitraum": "TAG",
  "netzebene": "HSP_MSP_UMSP",
  "umspannung": "MSP_NSP_UMSP",
  "datenstatusZeitreihe": "ABGERECHNETE_DATEN",
  "zuordnungsregel": "ENTGEGENGESETZTE_LIEFERRICHTUNG",
  "zeitreihenprodukt": [
    {
      "identifikation": "esse laboris do Ut",
      "korrekturfaktor": 10.75,
      "energiemenge": {
        "startdatum": "1924-11-09T05:56:57.0Z",
        "enddatum": "1918-10-08T01:25:15.0Z",
        "wertermittlungsverfahren": "PROGNOSE",
        "messwertstatus": "GRUNDLAGE_POG_ERMITTLUNG",
        "obiskennzahl": "ea cillum sunt elit eiusmod",
        "wert": 10.25,
        "einheit": "VARH",
        "type": "TUMKUNDENWERT",
        "tarifstufe": "TARIFSTUFE_7",
        "nutzungszeitpunkt": "1959-05-16T17:05:48.0Z",
        "ausfuehrungszeitpunkt": "1945-11-10T03:23:52.0Z",
        "position": 3897570520,
        "ablesedatum": "1939-11-30T01:01:08.0Z",
        "leistungsperiode": "258001",
        "statuszusatzinformationen": [
          {
            "art": "GASQUALITAET",
            "status": "STOERUNG_DEFEKT_MESSEINRICHTUNG"
          }
        ]
      },
      "jahresverbrauchsprognose": {
        "wert": 2.25,
        "einheit": "Z16",
        "startdatum": "1916-04-14T07:27:39.0Z",
        "enddatum": "1903-11-08T08:18:14.0Z"
      }
    }
  ]
}
