=== conuti-gmbh/bo4e-schema/schemas/schemas/v1/bo/AdHocSteuerkanal.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/AdHocSteuerkanal.schema.json",
  "title": "AdHocSteuerkanal",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "AD_HOC_STEUERKANAL"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "konfigurationsprodukt": {
      "type": "string",
      "faker": {
        "string.numeric": 14
      },
      "description": "konfigurationsprodukt"
    },
    "zieladresse": {
      "$ref": "../com/Zieladresse.schema.json"
    },
    "aussteller": {
      "$ref": "../com/Aussteller.schema.json"
    },
    "zertifikatsNutzer": {
      "$ref": "../com/ZertifikatsNutzer.schema.json"
    },
    "IPAdresseCLSDevice": {
      "$ref": "../com/IPAdresseCLSDevice.schema.json"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/AdHocSteuerkanal.json
{
  "boTyp": "AD_HOC_STEUERKANAL",
  "versionStruktur": "1",
  "konfigurationsprodukt": "33101747933462",
  "zieladresse": {
    "zieladresse1": "fugiat Duis",
    "zieladresse2": "eiusmod non pariatur sit",
    "zieladresse3": "exercitation quis laborum fugiat elit",
    "zieladresse4": "qui ad irure nisi mollit",
    "zieladresse5": "qui"
  },
  "aussteller": {
    "aussteller1": "magna in tempor",
    "aussteller2": "Ut",
    "aussteller3": "consectetur proident sed ad officia",
    "aussteller4": "id",
    "aussteller5": "culpa incididunt quis"
  },
  "zertifikatsNutzer": {
    "zertifikatsNutzer1": "ad enim ex aliqua elit",
    "zertifikatsNutzer2": "tempor laborum non dolore",
    "zertifikatsNutzer3": "dolor",
    "zertifikatsNutzer4": "id nulla culpa",
    "zertifikatsNutzer5": "consectetur dolor"
  },
  "IPAdresseCLSDevice": {
    "IPAdresseCLSDevice1": "in labore",
    "IPAdresseCLSDevice2": "eu magna",
    "IPAdresseCLSDevice3": "dolore ut consequat Lorem qui",
    "IPAdresseCLSDevice4": "consectetur dolore",
    "IPAdresseCLSDevice5": "sint laborum ex aliqua elit"
  }
}
