=== conuti-gmbh/bo4e-schema/schemas/schemas/v1/bo/Zaehler.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Zaehler.schema.json",
  "title": "Zaehler",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "ZAEHLER"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "zaehlernummer": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "ZAEHLER_",
          "length": 6
        }
      },
      "description": "Nummerierung des Zählers, vergeben durch den Messstellenbetreiber"
    },
    "sparte": {
      "$ref": "../enum/Sparte.schema.json",
      "description": "Strom oder Gas."
    },
    "zaehlerauspraegung": {
      "$ref": "../enum/Zaehlerauspraegung.schema.json",
      "description": "Spezifikation die Richtung des Zählers betreffend."
    },
    "zaehlertyp": {
      "$ref": "../enum/Zaehlertyp.schema.json",
      "description": "Typisierung des Zählers"
    },
    "tarifart": {
      "$ref": "../enum/Tarifart.schema.json",
      "description": "Spezifikation bezüglich unterstützter Tarifarten."
    },
    "zaehlerkonstante": {
      "type": "number",
      "format": "float",
      "faker": {
        "number.float": {
          "multipleOf": 0.5,
          "min": 10,
          "max": 30
        }
      },
      "description": "Zählerkonstante auf dem Zähler."
    },
    "eichungBis": {
      "type": "string",
      "format": "date-time",
      "description": "Bis zu diesem Datum ist der Zähler geeicht."
    },
    "zaehlerhersteller": {
      "$ref": "../bo/Geschaeftspartner.schema.json",
      "description": "Der Hersteller des Zählers. Details Geschaeftspartner"
    },
    "gateway": {
      "type": "string",
      "description": "Angabe eines SMGW, mit dem der Zaehler parametrisiert ist",
      "faker": {
        "string.binary": {
          "prefix": "GATEWAY_",
          "length": 6
        }
      }
    },
    "fernschaltung": {
      "$ref": "../enum/Fernschaltung.schema.json",
      "description": "Fernschaltung"
    },
    "messwerterfassung": {
      "$ref": "../enum/Messwerterfassung.schema.json",
      "description": "Messwerterfassung am Zählpunkt"
    },
    "zaehlertypspezifikation": {
      "$ref": "../enum/ZaehlertypSpezifikation.schema.json",
      "description": "Typisierung des Zählers (spezifikation für EHZ und MME)"
    },
    "befestigungsart": {
      "$ref": "../enum/Befestigungsart.schema.json",
      "description": "Befestigungsart"
    },
    "zaehlergroesse": {
      "$ref": "../enum/Geraetemerkmal.schema.json",
      "description": "Zaehlergroesse"
    },
    "mengenumwertertyp": {
      "$ref": "../enum/Mengenumwertertyp.schema.json"
    },
    "volumenerfassung": {
      "$ref": "../enum/Volumenerfassung.schema.json"
    },
    "serialnummer": {
      "type": "string",
      "faker": {
        "string.numeric": 10
      },
      "description": "serialnummer"
    },
    "geraetemerkmal": {
      "$ref": "../enum/Geraetemerkmal.schema.json",
      "description": "Weitere Merkmale des Geräts, zum Beispiel Mehrtarif, Eintarif etc.. Details Geraetemerkmal"
    },
    "herstellungsdatum": {
      "type": "string",
      "format": "date-time",
      "description": "herstellungsdatum"
    },
    "baujahr": {
      "type": "string",
      "$comment": "DTM+Z03",
      "description": "baujahr"
    },
    "messlokationsId": {
      "type": "string",
      "faker": {
        "string.numeric": 33
      },
      "description": "messlokationsId"
    },
    "marktlokationsId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      },
      "description": "marktlokationsId"
    },
    "geraete": {
      "type": "array",
      "items": {
        "$ref": "../com/Geraet.schema.json"
      },
      "description": "Liste der Geräte, die zu diesem Zähler gehören."
    },
    "zaehlwerke": {
      "type": "array",
      "items": {
        "$ref": "../com/Zaehlwerk.schema.json"
      },
      "description": "Die Zählwerke des Zählers."
    },
    "datenqualitaet": {
      "$ref": "../enum/Datenqualitaet.schema.json"
    },
    "gueltigkeitszeitraum": {
      "$ref": "../com/Zeitraum.schema.json"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Zaehler.json
{
  "boTyp": "ZAEHLER",
  "versionStruktur": "1",
  "zaehlernummer": "ZAEHLER_110111",
  "sparte": "ABWASSER",
  "zaehlerauspraegung": "EINRICHTUNGSZAEHLER",
  "zaehlertyp": "TURBINENRADGASZAEHLER",
  "tarifart": "LEISTUNGSGEMESSEN",
  "zaehlerkonstante": 21,
  "eichungBis": "7027",
  "zaehlerhersteller": {
    "boTyp": "GESCHAEFTSPARTNER",
    "versionStruktur": "1",
    "anrede": "Dr.",
    "name1": "Reichel",
    "name2": "Frida",
    "name3": "dolore minim in",
    "name4": "Ut do anim fugiat minim",
    "umsatzsteuerId": "DE001101110",
    "glaeubigerId": "631099",
    "emailAdresse": "Liv_Thieke@hotmail.com",
    "website": "https://herausragend-milchstrae.com/",
    "gewerbekennzeichnung": true,
    "hrnummer": "253971",
    "amtsgericht": "Bad Artur",
    "partneradresse": {
      "postleitzahl": "90304",
      "ort": "Gelsenkirchen",
      "strasse": "Kunstfeldstr.",
      "hausnummer": "16",
      "postfach": "laboris nostrud voluptate aliquip pariatur",
      "adresszusatz": "in fugiat",
      "coErgaenzung": "ad culpa nisi dolore consequat",
      "landescode": "NL",
      "ortsteil": "Speyer",
      "zusatzInformation": {
        "zusatz1": "voluptate Excepteur pariatur in",
        "zusatz2": "proident adipisicing Excepteur dolor",
        "zusatz3": "in",
        "zusatz4": "sit dolor",
        "zusatz5": "adipisicing"
      }
    },
    "externeKundenummerLieferant": "475410",
    "externeReferenzen": [
      {
        "exRefName": "Kundennummer beim Altlieferanten",
        "exRefWert": "6546732438"
      }
    ],
    "geschaeftspartnerrolle": [
      "DIENSTLEISTER"
    ],
    "kontaktweg": [
      "SMS"
    ],
    "ansprechpartner": {
      "boTyp": "ANSPRECHPARTNER",
      "versionStruktur": "1",
      "nachname": "Nitzsche",
      "eMailAdresse": "Ole10@hotmail.com",
      "rufnummern": [
        {
          "nummerntyp": "RUF_ZENTRALE",
          "rufnummer": "+49-9381-51966239"
        }
      ]
    }
  },
  "gateway": "GATEWAY_010111",
  "fernschaltung": "NICHT_VORHANDEN",
  "messwerterfassung": "FERNAUSLESBAR",
  "zaehlertypspezifikation": "MME_MEDA",
  "befestigungsart": "EINSTUTZEN",
  "zaehlergroesse": "GAS_G1600",
  "mengenumwertertyp": "DICHTEMENGENUMWERTER",
  "volumenerfassung": "HOCHFREQUENZSONDE",
  "serialnummer": "2118605314",
  "geraetemerkmal": "WASSER_VWZ07",
  "herstellungsdatum": "6691",
  "baujahr": "7116",
  "messlokationsId": "980964243790641598798980719201945",
  "marktlokationsId": "00551804105",
  "geraete": [
    {
      "geraetetyp": "VIER_QUADRANTEN_LASTGANGZAEHLER",
      "bezeichnung": "fugiat ea",
      "geraetenummer": "90103",
      "geraetereferenz": "REF_110000",
      "geraeteeigenschaften": {
        "geraetetyp": "OPTIONALE_ZUS_ZAEHLEINRICHTUNG",
        "geraetemerkmal": "GAS_G400",
        "volumenerfassung": "KENNLINIENKORREKTUR",
        "serialnummer": "5385342698",
        "herstellungsdatum": "9899",
        "baujahr": "4410",
        "eichungBis": "7951",
        "faktor": 8.25,
        "firmwareVersion": "FW_0011",
        "herstellerTypbezeichnung": "TYP_000011",
        "simKartenNummer": "97996390651363737810",
        "modemKennungIMSI": "703224349400006",
        "tkProvider": "TK_0101",
        "ipVersion": "3"
      },
      "volumenerfassung": "KENNLINIENKORREKTUR",
      "weitereGeraetenummern": [
        "30356"
      ]
    }
  ],
  "zaehlwerke": [
    {
      "zaehlwerkId": "184641158",
      "bezeichnung": "nisi officia nulla",
      "richtung": "AUSSP",
      "obisKennzahl": "consectetur nulla",
      "wandlerfaktor": 5,
      "einheit": "KUBIKMETER",
      "schwachlastfaehig": "NICHT_SCHWACHLASTFAEHIG",
      "verbrauchsart": [
        "W"
      ],
      "unterbrechbarkeit": "NUV",
      "waermenutzung": "WAERMEPUMPE",
      "konzessionsabgabe": {
        "satz": "TK",
        "kosten": 49508949.03705123,
        "kategorie": "voluptate"
      },
      "steuerbefreit": true,
      "vorkommastelle": 4,
      "nachkommastelle": 6,
      "abrechnungsrelevant": true,
      "anzahlAblesungen": 8,
      "zaehlzeiten": {
        "register": "ut esse nulla",
        "zaehlzeitDefinition": "fugiat amet id aliquip elit",
        "schwachlastfaehig": "NICHT_SCHWACHLASTFAEHIG"
      },
      "konfiguration": "dolore magna occaecat cupidatat Ut",
      "messprodukt": "mollit nulla dolore",
      "wertegranularitaet": "QUARTALSWEISE",
      "notwendigkeitZweiteMessung": "NICHT_VORHANDEN",
      "werteuebermittlungVerwendungszweck": "NICHT_VORHANDEN",
      "artEMobilitaet": "LP",
      "konfigurationsprodukt": "culpa Duis aute in",
      "keinKonfigurationsprodukt": false,
      "leistungskurvendefinition": "nostrud laboris incididunt ex",
      "verwendungszwecke": [
        {
          "marktrolle": "MSBA",
          "zweck": [
            "ENDKUNDENABRECHNUNG"
          ]
        }
      ],
      "verwendungszweckNB": "in dolor proident non",
      "verwendungszweckLF": "laborum officia Ut",
      "verwendungszweckUENB": "in",
      "keinProdukt": false
    }
  ],
  "datenqualitaet": "GUELTIGE_DATEN",
  "gueltigkeitszeitraum": {
    "zeiteinheit": "VIERTEL_STUNDE",
    "dauer": 3,
    "startdatum": "1948-01-10T20:34:53.0Z",
    "enddatum": "1921-06-09T20:47:44.0Z",
    "einheit": "VIERTEL_STUNDE",
    "ableseZeitraum": "941469",
    "abrechnungsZeitraum": "415598",
    "zeitraumText": "sed Excepteur",
    "zeitraumId": 3
  }
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Zaehler.json
{
  "boTyp": "ZAEHLER",
  "versionStruktur": "1",
  "zaehlernummer": "ZAEHLER_111001",
  "sparte": "WASSER",
  "zaehlerauspraegung": "ZWEIRICHTUNGSZAEHLER",
  "zaehlertyp": "ULTRASCHALLGASZAEHLER",
  "tarifart": "EINTARIF",
  "zaehlerkonstante": 26.5,
  "eichungBis": "1910-11-29T19:07:48.0Z",
  "zaehlerhersteller": {
    "boTyp": "GESCHAEFTSPARTNER",
    "versionStruktur": "1",
    "anrede": "Prof. Dr.",
    "name1": "Wiechmann",
    "name2": "Nila",
    "name3": "nostrud esse anim consectetur",
    "name4": "sit",
    "umsatzsteuerId": "DE100001101",
    "glaeubigerId": "471195",
    "emailAdresse": "Benno34@hotmail.com",
    "website": "https://cool-daumen.org",
    "gewerbekennzeichnung": true,
    "hrnummer": "783454",
    "amtsgericht": "Bad Alessialand",
    "partneradresse": {
      "postleitzahl": "41410",
      "ort": "Neu Luise",
      "strasse": "Reuschenberger Str.",
      "hausnummer": "14",
      "postfach": "Duis et ullamco",
      "adresszusatz": "amet incididunt",
      "coErgaenzung": "non esse mollit dolore",
      "landescode": "PW",
      "ortsteil": "Bad Mikailland",
      "zusatzInformation": {
        "zusatz1": "esse elit aute id",
        "zusatz2": "esse labore aliqua consequat",
        "zusatz3": "adipisicing",
        "zusatz4": "tempor voluptate sit pariatur eu",
        "zusatz5": "laborum aliqua"
      }
    },
    "externeKundenummerLieferant": "678399",
    "externeReferenzen": [
      {
        "exRefName": "Kundennummer beim Altlieferanten",
        "exRefWert": "4420749928"
      }
    ],
    "geschaeftspartnerrolle": [
      "LIEFERANT"
    ],
    "kontaktweg": [
      "E_MAIL"
    ]
  },
  "gateway": "GATEWAY_100001",
  "fernschaltung": "VORHANDEN",
  "messwerterfassung": "FERNAUSLESBAR",
  "zaehlertypspezifikation": "MME_MEDA",
  "befestigungsart": "DREIPUNKT",
  "zaehlergroesse": "MODEM_GSM_O_LG",
  "mengenumwertertyp": "DICHTEMENGENUMWERTER",
  "volumenerfassung": "HOCHFREQUENZSONDE",
  "serialnummer": "6731227761",
  "geraetemerkmal": "WASSER_WZ03",
  "herstellungsdatum": "1947-07-01T15:15:55.0Z",
  "baujahr": "dolore occaecat",
  "messlokationsId": "297319823173905782929102230489500",
  "marktlokationsId": "18669824974",
  "geraete": [
    {
      "geraetetyp": "OPTIONALE_ZUS_ZAEHLEINRICHTUNG",
      "bezeichnung": "ex labore",
      "geraetenummer": "03395",
      "geraetereferenz": "REF_101110",
      "geraeteeigenschaften": {
        "geraetetyp": "KOMBIMESSWANDLER_IMS_MME",
        "geraetemerkmal": "GAS_G650",
        "faktor": 1.5
      },
      "volumenerfassung": "KENNLINIENKORREKTUR",
      "weitereGeraetenummern": [
        "17927"
      ]
    }
  ],
  "zaehlwerke": [
    {
      "zaehlwerkId": "922904359",
      "bezeichnung": "enim aute ea",
      "richtung": "AUSSP",
      "obisKennzahl": "et",
      "wandlerfaktor": 1,
      "einheit": "KWHK",
      "schwachlastfaehig": "NICHT_SCHWACHLASTFAEHIG",
      "verbrauchsart": "SW",
      "unterbrechbarkeit": "UV",
      "waermenutzung": "WAERMEPUMPE_KAELTE",
      "konzessionsabgabe": {
        "satz": "KAS",
        "kosten": -95596172.61968611,
        "kategorie": "Ut aute est reprehenderit"
      },
      "steuerbefreit": false,
      "vorkommastelle": 5,
      "nachkommastelle": 8,
      "abrechnungsrelevant": true,
      "anzahlAblesungen": 5,
      "zaehlzeiten": {
        "register": "pariatur non officia",
        "zaehlzeitDefinition": "dolor do laborum mollit",
        "schwachlastfaehig": "SCHWACHLASTFAEHIG"
      },
      "konfiguration": "aute cupidatat nulla Excepteur eu",
      "messprodukt": "velit cillum consequat dolor in",
      "wertegranularitaet": "JAEHRLICH",
      "notwendigkeitZweiteMessung": "VORHANDEN",
      "werteuebermittlungVerwendungszweck": "VORHANDEN",
      "artEMobilitaet": "WB",
      "konfigurationsprodukt": "ullamco in",
      "keinKonfigurationsprodukt": false,
      "leistungskurvendefinition": "elit sint dolor",
      "verwendungszwecke": [
        {
          "marktrolle": "DL",
          "zweck": [
            "NETZNUTZUNGSABRECHNUNG"
          ]
        }
      ]
    }
  ],
  "datenqualitaet": "KEINE_DATEN_ERWARTET",
  "gueltigkeitszeitraum": {
    "zeiteinheit": "VIERTEL_STUNDE",
    "dauer": 2,
    "startdatum": "1959-04-08T05:57:32.0Z",
    "enddatum": "1890-09-27T10:56:46.0Z",
    "einheit": "JAHR",
    "ableseZeitraum": "964360",
    "abrechnungsZeitraum": "454763",
    "zeitraumText": "laboris aliqua aliquip ea anim",
    "zeitraumId": 9
  }
}
